version: '3.3'

services:
  app:
    build:
      context: .
            
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - static-data:/vol/web
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - THROTTLE_ANON=${THROTTLE_ANON}
      - THROTTLE_USER=${THROTTLE_USER}
      - RESIZE_URL={RESIZE_URL}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  postgres-data:
  static-data: